services:
  - type: web
    name: acoustic-shazam
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
      - key: SHAZAM_EXECUTABLE_PATH
        value: /app/cpp_engine/shazam
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
      - key: UPLOAD_DIR
        value: /tmp/shazam_uploads
