spring.mongodb.uri=mongodb://localhost:27017/shazamdb
file.upload-dir=./uploads
# Set the max file size for a single file (e.g., 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Set the max request size for a single request (useful if uploading multiple files)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB