spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/shazamdb}
file.upload-dir=${UPLOAD_DIR:./uploads}
shazam.executable.path=${SHAZAM_EXECUTABLE_PATH:C:/Users/khali/OneDrive/Bureau/learning/spring/shazam/backend/cpp_engine/shazam.exe}
server.port=${PORT:8080}
spring.data.mongodb.auto-index-creation=true

# Set the max file size for a single file (e.g., 500 Megabytes)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB